// Ajent Signals — Cloudflare Worker. Cron trigger runs the 24/7 paper-trading loop;
// the HTTP handler serves the Pro-gated /signals and /trades endpoints.
import { db } from './db.js';
import { runTick } from './scheduler.js';
import { requirePro } from './auth.js';
import { registerWebhook, listWebhooks, deleteWebhook, deliverEvents, sampleEvent, EDU_DISCLAIMER } from './webhooks.js';
import { createCheckoutSession, verifyStripeSignature, handleStripeEvent, tokenForSession, refreshToken, validateApple, validateGoogle } from './billing.js';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Authorization,Content-Type',
  'Access-Control-Allow-Methods': 'GET,POST,DELETE,OPTIONS',
};
const json = (body, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...CORS, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' } });

async function readJson(request) {
  try { return (await request.json()) || {}; } catch (e) { return {}; }
}

// Rides along on every data response so the published data is never presented as
// licensed real-time data or as advice — protects us on both the data-licensing
// and the financial-advice fronts.
const NOTICE = {
  disclaimer: 'Educational and simulated. Signals are hypothetical, generated by quantitative models, and are NOT investment advice or a recommendation. Ajent Signals is not a registered investment adviser or broker, places no real orders, and holds no funds. Past/simulated results do not guarantee future performance.',
  data: 'Market data is DELAYED and derived from public sources for educational use only — it is not licensed real-time market data. Not for redistribution or resale.',
};

function summarize(closed) {
  const wins = closed.filter((c) => c.pnl > 0), losses = closed.filter((c) => c.pnl < 0);
  const gw = wins.reduce((s, c) => s + c.pnl, 0), gl = Math.abs(losses.reduce((s, c) => s + c.pnl, 0));
  const dec = wins.length + losses.length;
  return { trades: closed.length, winRate: dec ? Math.round((wins.length / dec) * 100) : 0, profitFactor: gl > 0 ? +(gw / gl).toFixed(2) : (gw > 0 ? null : 0), totalPnl: closed.reduce((s, c) => s + (c.pnl || 0), 0) };
}

export default {
  // Cron: '*/15 * * * *' — the 24/7 loop, whether or not anyone's app is open.
  async scheduled(event, env, ctx) {
    ctx.waitUntil(runTick(env, db(env)));
  },

  async fetch(request, env) {
    if (request.method === 'OPTIONS') return new Response(null, { headers: CORS });
    const url = new URL(request.url);
    if (url.pathname === '/health') return json({ ok: true });

    // --- Billing (UNGATED — this is how a user BECOMES Pro) ---------------------
    if (url.pathname.startsWith('/billing/')) {
      const store = db(env);
      try {
        if (url.pathname === '/billing/checkout' && request.method === 'POST') {
          const b = await readJson(request);
          const r = await createCheckoutSession(env, { plan: b.plan, successUrl: b.successUrl, cancelUrl: b.cancelUrl, ref: b.ref });
          return json(r.error ? { error: r.error } : r, r.error ? (r.status || 400) : 200);
        }
        if (url.pathname === '/billing/webhook' && request.method === 'POST') {
          const raw = await request.text();
          const sig = request.headers.get('Stripe-Signature');
          if (!(await verifyStripeSignature(raw, sig, env.STRIPE_WEBHOOK_SECRET))) return json({ error: 'bad signature' }, 400);
          const event = JSON.parse(raw);
          const status = await handleStripeEvent(env, store, event);
          return json({ received: true, status });
        }
        if (url.pathname === '/billing/config' && request.method === 'GET') {
          // Tells the app whether a real purchase path exists yet, so the paywall
          // shows "Join the waitlist" (not a failing checkout) until Stripe is set.
          const realPrice = (p) => !!p && !/REPLACE/.test(p);
          const checkout = !!(env.STRIPE_SECRET_KEY && (realPrice(env.STRIPE_PRICE_MONTHLY) || realPrice(env.STRIPE_PRICE_ANNUAL)));
          return json({ checkout, gated: !!env.PRO_SECRET });
        }
        if (url.pathname === '/billing/status' && request.method === 'GET') {
          // Definitive entitlement check for the client — lets the app clear a
          // faked/expired local token instead of trusting it. Ungated on purpose
          // (you must be able to learn you are NOT entitled).
          const gate = await requirePro(request, env);
          return json({ entitled: !!gate.ok });
        }
        if (url.pathname === '/billing/token' && request.method === 'GET') {
          const r = await tokenForSession(store, url.searchParams.get('session_id') || '');
          return r ? json(r) : json({ error: 'not ready' }, 404);
        }
        if (url.pathname === '/billing/refresh' && request.method === 'POST') {
          const b = await readJson(request);
          const tok = b.token || (request.headers.get('Authorization') || '').replace(/^Bearer\s+/i, '').trim();
          const r = await refreshToken(env, store, tok);
          return r ? json(r) : json({ error: 'no active entitlement' }, 404);
        }
        if (url.pathname === '/billing/apple' && request.method === 'POST') {
          const b = await readJson(request);
          const r = await validateApple(env, { receipt: b.receipt, sub: b.sub });
          return json(r, r.error ? (r.status || 400) : 200);
        }
        if (url.pathname === '/billing/google' && request.method === 'POST') {
          const b = await readJson(request);
          const r = await validateGoogle(env, { purchaseToken: b.purchaseToken, productId: b.productId, sub: b.sub });
          return json(r, r.error ? (r.status || 400) : 200);
        }
      } catch (e) { return json({ error: String(e && e.message || e) }, 500); }
      return json({ error: 'not found' }, 404);
    }

    // Pro gate — the backend IS the Pro feature. Free users run client-side.
    const gate = await requirePro(request, env);
    if (!gate.ok) return json({ error: 'Ajent Pro required', reason: gate.reason }, 402);

    const store = db(env);
    const sub = gate.sub || 'anon';
    if (url.pathname === '/signals') {
      const blob = await store.get('SIGNALS', 'ALL'); // single batched blob (1 KV read)
      return json({ updatedAt: (blob && blob.updatedAt) || Date.now(), signals: (blob && blob.signals) || [], notice: NOTICE });
    }
    if (url.pathname === '/trades') {
      const open = await store.list('POS#OPEN');
      const closed = (await store.list('TRADE')).sort((a, b) => b.closedAt - a.closedAt).slice(0, 200);
      return json({ open, closed, summary: summarize(closed), notice: NOTICE });
    }

    // --- Signal-export webhooks (Pro "API into your own tooling") ---------------
    if (url.pathname === '/webhooks') {
      if (request.method === 'GET') {
        const hooks = await listWebhooks(store, sub);
        return json({ webhooks: hooks, disclaimer: EDU_DISCLAIMER });
      }
      if (request.method === 'POST') {
        const b = await readJson(request);
        const r = await registerWebhook(store, sub, { url: b.url, events: b.events });
        if (r.error) return json({ error: r.error }, r.status || 400);
        // secret is shown once here so the user can verify our signatures.
        return json({ webhook: r.hook, note: 'Save the secret — verify X-Ajent-Signature = sha256(HMAC-SHA256(rawBody, secret)).' }, 201);
      }
    }
    // /webhooks/<id> (DELETE) and /webhooks/test (POST a sample to all hooks)
    const m = url.pathname.match(/^\/webhooks\/([\w-]+)$/);
    if (m) {
      const id = m[1];
      if (id === 'test' && request.method === 'POST') {
        const r = await deliverEvents(store, [sampleEvent()], { onlySub: sub });
        return json({ ok: true, delivered: r.delivered, sample: sampleEvent() });
      }
      if (request.method === 'DELETE') {
        const r = await deleteWebhook(store, sub, id);
        return json(r.error ? { error: r.error } : { ok: true }, r.status || 200);
      }
    }
    return json({ error: 'not found' }, 404);
  },
};
