// Ajent Signals — Cloudflare Worker. Cron trigger runs the 24/7 paper-trading loop;
// the HTTP handler serves the Pro-gated /signals and /trades endpoints.
import { db } from './db.js';
import { runTick } from './scheduler.js';
import { runDayTick } from './daytradeScheduler.js';
import { scanStocks } from './stocks.js';
import { MARKETS } from './markets.js';
import { STRATEGY, publicStrategy, publicSignal, publicPosition } from './meta.js';
import { addSubscription, removeSubscription, pushToAll } from './push.js';
import { requirePro } from './auth.js';
import { registerWebhook, listWebhooks, deleteWebhook, deliverEvents, sampleEvent, EDU_DISCLAIMER } from './webhooks.js';
import { createCheckoutSession, verifyStripeSignature, handleStripeEvent, tokenForSession, refreshToken, validateApple, validateGoogle } from './billing.js';

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'Authorization,Content-Type',
  'Access-Control-Allow-Methods': 'GET,POST,DELETE,OPTIONS',
};
const json = (body, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { ...CORS, 'Content-Type': 'application/json', 'Cache-Control': 'no-store' } });

async function readJson(request) {
  try { return (await request.json()) || {}; } catch (e) { return {}; }
}

// Rides along on every data response so the published data is never presented as
// licensed real-time data or as advice — protects us on both the data-licensing
// and the financial-advice fronts.
const NOTICE = {
  disclaimer: 'Educational and simulated. Signals are hypothetical, generated by quantitative models, and are NOT investment advice or a recommendation. Ajent Signals is not a registered investment adviser or broker, places no real orders, and holds no funds. Past/simulated results do not guarantee future performance.',
  data: 'Market data is DELAYED and derived from public sources for educational use only — it is not licensed real-time market data. Not for redistribution or resale.',
};

function summarize(closed) {
  const wins = closed.filter((c) => c.pnl > 0), losses = closed.filter((c) => c.pnl < 0);
  const gw = wins.reduce((s, c) => s + c.pnl, 0), gl = Math.abs(losses.reduce((s, c) => s + c.pnl, 0));
  const dec = wins.length + losses.length;
  return { trades: closed.length, winRate: dec ? Math.round((wins.length / dec) * 100) : 0, profitFactor: gl > 0 ? +(gw / gl).toFixed(2) : (gw > 0 ? null : 0), totalPnl: closed.reduce((s, c) => s + (c.pnl || 0), 0) };
}

export default {
  // Cron: '*/15 * * * *' — the 24/7 loop, whether or not anyone's app is open.
  async scheduled(event, env, ctx) {
    ctx.waitUntil((async () => {
      const store = db(env);
      // A thrown tick must not go unnoticed — log it. The next cron run retries; the
      // record is only rewritten on a clean pass, so a failure never corrupts state.
      let r;
      try { r = await runTick(env, store); }
      catch (e) { console.error('runTick failed:', e && e.stack || e); return; }
      // The intraday day-trading EXPERIMENT runs on its own isolated record — a
      // failure here must never affect the proven Swing loop above, so it's fully
      // wrapped and its outcome is not allowed to change Swing's push behaviour.
      try { await runDayTick(env, store); }
      catch (e) { console.error('runDayTick failed:', e && e.stack || e); }
      // Stock-screener scan — once per calendar day, fully isolated (signals only, its
      // own blob, never touches the traded record). A failure can't affect Swing.
      try {
        const sBlob = await store.get('SIGNALS_STOCKS', 'ALL');
        const today = new Date().toISOString().slice(0, 10);
        if (!sBlob || sBlob.day !== today) {
          const stocks = await scanStocks(env);
          if (stocks.length) await store.put({ pk: 'SIGNALS_STOCKS', sk: 'ALL', day: today, at: Date.now(), stocks });
        }
      } catch (e) { console.error('stock scan failed:', e && e.stack || e); }
      // Ping push subscribers only when a fresh BUY/SELL actually fires. Record
      // WHAT fired so the notification can name the market(s), not just "a setup".
      if (r && r.signalFired) {
        try { await store.put({ pk: 'PUSH', sk: 'LAST', fired: r.fired, at: Date.now() }); } catch (e) { /* non-fatal */ }
        try { await pushToAll(env, store); } catch (e) { /* never block the loop */ }
      }
    })());
  },

  async fetch(request, env) {
    if (request.method === 'OPTIONS') return new Response(null, { headers: CORS });
    const url = new URL(request.url);
    if (url.pathname === '/health') return json({ ok: true });

    // Force one run of the 24/7 loop on demand (e.g. right after a deploy) instead
    // of waiting for the next 15-min cron. Guarded by its own ADMIN_KEY secret —
    // separate from the Pro gate, so it never affects free access. No-op (404) when
    // the secret isn't configured, so it can't be abused to spin KV writes.
    if (url.pathname === '/admin/tick') {
      if (!env.ADMIN_KEY || url.searchParams.get('key') !== env.ADMIN_KEY) return json({ error: 'not found' }, 404);
      const store = db(env);
      const r = await runTick(env, store);
      let day = null;
      try { day = await runDayTick(env, store); } catch (e) { day = { error: String(e && e.message || e) }; }
      return json({ ok: true, ...r, day });
    }

    // The intraday day-trading EXPERIMENT — its live signals (recipe stripped) and
    // its OWN tracked paper record. UNGATED on purpose: an unproven experiment we do
    // not advertise should be fully transparent, so anyone can see exactly how it is
    // doing on a real live record. Numbers here are the honest live paper result —
    // never a backtest headline. The exact stop/exit dials are stripped, same as
    // /signals, so the proprietary recipe still never leaves the server.
    if (url.pathname === '/day') {
      const store = db(env);
      const sigBlob = await store.get('SIGNALS_DAY', 'ALL');
      const recBlob = await store.get('RECORD_DAY', 'ALL');
      const signals = ((sigBlob && sigBlob.signals) || []).map(publicSignal);
      const open = recBlob && recBlob.open ? Object.values(recBlob.open).map(publicPosition) : [];
      const closed = (recBlob && recBlob.closed ? recBlob.closed : []).slice(0, 100).map(publicPosition);
      return json({
        updatedAt: (sigBlob && sigBlob.updatedAt) || Date.now(),
        experiment: true,
        status: 'EXPERIMENTAL — not proven. Both-directional intraday mean-reversion on 15-minute bars, flat by the close (no overnight risk). Tracked live on this record; results are provisional and are NOT a recommendation.',
        signals, open, closed,
        summary: (sigBlob && sigBlob.summary) || summarize(closed),
        notice: NOTICE,
      });
    }

    // Real-time crypto quotes, fetched server-side (the browser can't reach Yahoo
    // directly — CORS — and the free proxies are unreliable). Restricted to the
    // known crypto symbols so it can't be abused as an open proxy. Ungated: this
    // is just a price, and crypto's feed has no exchange delay, so it lets the app
    // tick BTC/ETH live between the 5-min signal ticks.
    // Per-market signal timeline — meaningful transitions logged over time. Ungated.
    if (url.pathname === '/history') {
      const sym = url.searchParams.get('symbol') || '';
      const blob = await db(env).get('HISTORY', 'ALL');
      const hist = (blob && blob.hist) || {};
      return json({ symbol: sym, events: (sym ? hist[sym] : null) || [] });
    }

    // Daily stock screener — the proven swing strategy scanned across a diversified
    // large-cap universe. SIGNALS ONLY (not auto-traded; single-name risk needs
    // guardrails), recipe stripped like /signals. Ungated + transparent.
    if (url.pathname === '/stocks') {
      const blob = await db(env).get('SIGNALS_STOCKS', 'ALL');
      // Strip the recipe reading (rsi2) here too — defence in depth, so even a blob
      // scanned by an older build is served clean (guarded by test/no-recipe-leak).
      const stocks = ((blob && blob.stocks) || []).map(({ rsi2, ...row }) => row);
      return json({
        updatedAt: (blob && blob.at) || 0,
        day: (blob && blob.day) || null,
        experiment: true,
        status: 'SCREENER — the proven swing strategy scanned across a diversified large-cap universe, refreshed daily. These are signals to consider, NOT auto-traded into the tracked record. Educational, not advice.',
        stocks,
        notice: NOTICE,
      });
    }

    if (url.pathname === '/live') {
      // Crypto trades 24/7 with no exchange delay — Yahoo serves it real-time.
      const CRYPTO = { BTC: 'BTC-USD', ETH: 'ETH-USD' };
      // US index futures: the free futures feed is ~15 min delayed, but the tracking
      // ETF (SPY≈ES, QQQ≈NQ, DIA≈YM, IWM≈RTY) quotes fresher. We apply the ETF's
      // real-time % move to the future's OWN settled prior close for a near-real-time
      // ESTIMATE — labelled as a proxy, never presented as the exact futures print.
      const PROXY = { ES: 'SPY', NQ: 'QQQ', YM: 'DIA', RTY: 'IWM' };
      const FUT = { ES: 'ES=F', NQ: 'NQ=F', YM: 'YM=F', RTY: 'RTY=F' };
      const quotes = {};

      const yq = async (sym) => {
        try {
          const r = await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${sym}`, { headers: { 'User-Agent': 'ajent-signals-worker/1.0' }, cf: { cacheTtl: 8, cacheEverything: true } });
          const meta = (await r.json())?.chart?.result?.[0]?.meta;
          if (meta && typeof meta.regularMarketPrice === 'number') {
            return { price: meta.regularMarketPrice, prevClose: meta.chartPreviousClose ?? meta.previousClose ?? null, at: meta.regularMarketTime ? meta.regularMarketTime * 1000 : Date.now() };
          }
        } catch (e) { /* skip */ }
        return null;
      };
      // Real-time ETF quote: guaranteed real-time via Finnhub if FINNHUB_KEY is set,
      // otherwise Yahoo (which serves US ETFs fresher than delayed CME futures).
      const etfQuote = async (etf) => {
        if (env.FINNHUB_KEY) {
          try {
            const r = await fetch(`https://finnhub.io/api/v1/quote?symbol=${etf}&token=${env.FINNHUB_KEY}`, { cf: { cacheTtl: 8, cacheEverything: true } });
            const j = await r.json();
            if (j && typeof j.c === 'number' && j.c > 0 && typeof j.pc === 'number' && j.pc > 0) {
              return { price: j.c, prevClose: j.pc, at: j.t ? j.t * 1000 : Date.now() };
            }
          } catch (e) { /* fall through to Yahoo */ }
        }
        return yq(etf);
      };

      await Promise.all([
        ...Object.entries(CRYPTO).map(async ([sym, y]) => {
          const q = await yq(y);
          if (q) quotes[sym] = { price: q.price, prevClose: q.prevClose, at: q.at };
        }),
        ...Object.entries(PROXY).map(async ([sym, etf]) => {
          const [etfQ, futQ] = await Promise.all([etfQuote(etf), yq(FUT[sym])]);
          if (!etfQ || !futQ || !(etfQ.prevClose > 0) || !(futQ.prevClose > 0)) return;
          // Only override when the proxy is genuinely FRESHER than the delayed
          // future (>1 min) — otherwise it adds nothing; leave the future delayed.
          if (!(etfQ.at > futQ.at + 60000)) return;
          const pct = (etfQ.price - etfQ.prevClose) / etfQ.prevClose;
          const est = futQ.prevClose * (1 + pct);
          quotes[sym] = { price: +est.toFixed(2), prevClose: futQ.prevClose, at: etfQ.at, proxy: etf, pct: +(pct * 100).toFixed(2) };
        }),
      ]);
      return json({ quotes, at: Date.now() });
    }

    // --- Web push (signal alerts when the app is closed) -----------------------
    if (url.pathname === '/push/config') {
      return json({ key: env.VAPID_PUBLIC || '', enabled: !!(env.VAPID_PUBLIC && env.VAPID_JWK) });
    }
    if (url.pathname === '/push/subscribe' && request.method === 'POST') {
      try { const sub = await readJson(request); const ok = await addSubscription(db(env), sub && sub.subscription ? sub.subscription : sub); return json({ ok }); }
      catch (e) { return json({ error: 'bad subscription' }, 400); }
    }
    if (url.pathname === '/push/unsubscribe' && request.method === 'POST') {
      try { const b = await readJson(request); await removeSubscription(db(env), b && b.endpoint); return json({ ok: true }); }
      catch (e) { return json({ ok: true }); }
    }
    if (url.pathname === '/push/last') {
      const blob = await db(env).get('PUSH', 'LAST');
      return json({ fired: (blob && blob.fired) || [], at: (blob && blob.at) || 0 });
    }
    if (url.pathname === '/push/test') {
      if (!env.ADMIN_KEY || url.searchParams.get('key') !== env.ADMIN_KEY) return json({ error: 'not found' }, 404);
      const r = await pushToAll(env, db(env));
      return json({ ok: true, ...r });
    }

    // Market news, fetched server-side (no browser CORS), aggregated across a few
    // market queries, deduped and time-sorted. Real headlines from a public source,
    // each linking back to its publisher — never fabricated. Edge-cached ~5m.
    if (url.pathname === '/news') {
      const QUERIES = ['S&P 500', 'stock market today', 'Nasdaq', 'Wall Street'];
      // Keep genuine market/macro headlines; drop the single-company / off-topic
      // noise Yahoo's search mixes in.
      const RELEVANT = /\b(stock|stocks|market|markets|s&p|s\s?&\s?p|nasdaq|dow|wall street|fed|federal reserve|rate cut|rate hike|interest rate|futures|index|indexes|inflation|cpi|jobs report|payroll|treasur|yield|rally|sell-?off|selloff|bull|bear|earnings|gdp|recession|tariff|oil|crude)\b/i;
      const seen = new Set(), items = [];
      await Promise.all(QUERIES.map(async (q) => {
        try {
          const r = await fetch(`https://query1.finance.yahoo.com/v1/finance/search?q=${encodeURIComponent(q)}&newsCount=10&quotesCount=0`, { headers: { 'User-Agent': 'ajent-signals-worker/1.0' }, cf: { cacheTtl: 300, cacheEverything: true } });
          const news = (await r.json())?.news || [];
          for (const n of news) {
            if (!n.title || !n.link || seen.has(n.link) || !RELEVANT.test(n.title)) continue;
            seen.add(n.link);
            items.push({ title: n.title, publisher: n.publisher || '', link: n.link, time: (n.providerPublishTime || 0) * 1000 });
          }
        } catch (e) { /* skip this query */ }
      }));
      items.sort((a, b) => b.time - a.time);
      return json({ news: items.slice(0, 12), at: Date.now(), source: 'Yahoo Finance (public)' });
    }

    // Real OHLC candles for the charts, fetched server-side (no browser CORS,
    // edge-cached). Keyed by the APP symbol so the chart uses the SAME instrument
    // the strategy trades (e.g. RTY -> RTY=F), keeping the chart on the same scale
    // as the daily history and trade markers. Ungated — it's just price history.
    if (url.pathname === '/candles') {
      const sym = url.searchParams.get('symbol') || '';
      const interval = url.searchParams.get('interval') || '15m';
      const range = url.searchParams.get('range') || '1mo';
      const meta = MARKETS[sym];
      if (!meta) return json({ error: 'unknown symbol' }, 400);
      if (!/^(1m|2m|5m|15m|30m|60m|90m|1h|1d)$/.test(interval) || !/^(1d|5d|1mo|3mo|6mo|1y|2y)$/.test(range)) return json({ error: 'bad params' }, 400);
      try {
        const r = await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(meta.yahoo)}?interval=${interval}&range=${range}`, { headers: { 'User-Agent': 'ajent-signals-worker/1.0' }, cf: { cacheTtl: 60, cacheEverything: true } });
        const result = (await r.json())?.chart?.result?.[0];
        if (!result || !result.timestamp) return json({ candles: [] });
        const ts = result.timestamp, q = result.indicators.quote[0], out = [];
        for (let i = 0; i < ts.length; i++) {
          if (q.close[i] == null) continue;
          out.push({ t: ts[i], o: q.open[i] ?? q.close[i], h: q.high[i] ?? q.close[i], l: q.low[i] ?? q.close[i], c: q.close[i], v: (q.volume && q.volume[i]) || 0 });
        }
        return json({ candles: out });
      } catch (e) { return json({ candles: [] }); }
    }

    // --- Billing (UNGATED — this is how a user BECOMES Pro) ---------------------
    if (url.pathname.startsWith('/billing/')) {
      const store = db(env);
      try {
        if (url.pathname === '/billing/checkout' && request.method === 'POST') {
          const b = await readJson(request);
          const r = await createCheckoutSession(env, { plan: b.plan, successUrl: b.successUrl, cancelUrl: b.cancelUrl, ref: b.ref });
          return json(r.error ? { error: r.error } : r, r.error ? (r.status || 400) : 200);
        }
        if (url.pathname === '/billing/webhook' && request.method === 'POST') {
          const raw = await request.text();
          const sig = request.headers.get('Stripe-Signature');
          if (!(await verifyStripeSignature(raw, sig, env.STRIPE_WEBHOOK_SECRET))) return json({ error: 'bad signature' }, 400);
          const event = JSON.parse(raw);
          const status = await handleStripeEvent(env, store, event);
          return json({ received: true, status });
        }
        if (url.pathname === '/billing/config' && request.method === 'GET') {
          // Tells the app whether a real purchase path exists yet, so the paywall
          // shows "Join the waitlist" (not a failing checkout) until Stripe is set.
          const realPrice = (p) => !!p && !/REPLACE/.test(p);
          const checkout = !!(env.STRIPE_SECRET_KEY && (realPrice(env.STRIPE_PRICE_MONTHLY) || realPrice(env.STRIPE_PRICE_ANNUAL)));
          return json({ checkout, gated: !!env.PRO_SECRET });
        }
        if (url.pathname === '/billing/status' && request.method === 'GET') {
          // Definitive entitlement check for the client — lets the app clear a
          // faked/expired local token instead of trusting it. Ungated on purpose
          // (you must be able to learn you are NOT entitled).
          const gate = await requirePro(request, env);
          return json({ entitled: !!gate.ok });
        }
        if (url.pathname === '/billing/token' && request.method === 'GET') {
          const r = await tokenForSession(store, url.searchParams.get('session_id') || '');
          return r ? json(r) : json({ error: 'not ready' }, 404);
        }
        if (url.pathname === '/billing/refresh' && request.method === 'POST') {
          const b = await readJson(request);
          const tok = b.token || (request.headers.get('Authorization') || '').replace(/^Bearer\s+/i, '').trim();
          const r = await refreshToken(env, store, tok);
          return r ? json(r) : json({ error: 'no active entitlement' }, 404);
        }
        if (url.pathname === '/billing/apple' && request.method === 'POST') {
          const b = await readJson(request);
          const r = await validateApple(env, { receipt: b.receipt, sub: b.sub });
          return json(r, r.error ? (r.status || 400) : 200);
        }
        if (url.pathname === '/billing/google' && request.method === 'POST') {
          const b = await readJson(request);
          const r = await validateGoogle(env, { purchaseToken: b.purchaseToken, productId: b.productId, sub: b.sub });
          return json(r, r.error ? (r.status || 400) : 200);
        }
      } catch (e) { return json({ error: String(e && e.message || e) }, 500); }
      return json({ error: 'not found' }, 404);
    }

    // Pro gate — the backend IS the Pro feature. Free users run client-side.
    const gate = await requirePro(request, env);
    if (!gate.ok) return json({ error: 'Ajent Pro required', reason: gate.reason }, 402);

    const store = db(env);
    const sub = gate.sub || 'anon';
    if (url.pathname === '/signals') {
      const blob = await store.get('SIGNALS', 'ALL'); // single batched blob (1 KV read)
      // `strategy` = the single source of truth for the strategy's parameters, so
      // the app's copy and its book-profit/stop logic always match what runs here.
      // The EVOLVED dials (learned globally from all trades) are merged in, so the
      // app shows the current, adapted strategy — not just the frozen defaults.
      const a = blob && blob.adaptive;
      // Send only the GENERALIZED public strategy — the exact indicators/thresholds/
      // stop (the proprietary recipe) never leave the server. Strip the exit
      // threshold from each signal's plan too; book-profit/cut is computed
      // server-side and delivered as an `action` on open positions (/trades).
      const strategy = publicStrategy(a);
      // Allowlist projection — strips the raw indicator readings (rsi2/pctB), the
      // trend-MA value, and the plan's hidden dials so the recipe never leaves here.
      const signals = ((blob && blob.signals) || []).map(publicSignal);
      return json({ updatedAt: (blob && blob.updatedAt) || Date.now(), signals, strategy, notice: NOTICE });
    }
    if (url.pathname === '/trades') {
      try {
        // Single batched blob (1 KV get) — no KV list(), which is capped at
        // 1,000/day on the free tier and was throwing here under normal polling.
        const rec = await store.get('RECORD', 'ALL');
        // Strip recipe-revealing fields from open positions (exit threshold, exit rule
        // name, hold cap). The client uses the derived `call` the scheduler set instead.
        const open = rec && rec.open ? Object.values(rec.open).map(publicPosition) : [];
        const closed = (rec && rec.closed ? rec.closed : []).slice(0, 200).map(publicPosition);
        return json({ open, closed, summary: summarize(closed), notice: NOTICE });
      } catch (e) { return json({ error: 'trades: ' + String((e && e.message) || e).slice(0, 200) }, 500); }
    }

    // --- Signal-export webhooks (Pro "API into your own tooling") ---------------
    if (url.pathname === '/webhooks') {
      if (request.method === 'GET') {
        const hooks = await listWebhooks(store, sub);
        return json({ webhooks: hooks, disclaimer: EDU_DISCLAIMER });
      }
      if (request.method === 'POST') {
        const b = await readJson(request);
        const r = await registerWebhook(store, sub, { url: b.url, events: b.events });
        if (r.error) return json({ error: r.error }, r.status || 400);
        // secret is shown once here so the user can verify our signatures.
        return json({ webhook: r.hook, note: 'Save the secret — verify X-Ajent-Signature = sha256(HMAC-SHA256(rawBody, secret)).' }, 201);
      }
    }
    // /webhooks/<id> (DELETE) and /webhooks/test (POST a sample to all hooks)
    const m = url.pathname.match(/^\/webhooks\/([\w-]+)$/);
    if (m) {
      const id = m[1];
      if (id === 'test' && request.method === 'POST') {
        const r = await deliverEvents(store, [sampleEvent()], { onlySub: sub });
        return json({ ok: true, delivered: r.delivered, sample: sampleEvent() });
      }
      if (request.method === 'DELETE') {
        const r = await deleteWebhook(store, sub, id);
        return json(r.error ? { error: r.error } : { ok: true }, r.status || 200);
      }
    }
    return json({ error: 'not found' }, 404);
  },
};
